" gvim on windows: copy this file as Users/user/_vimrc
" neovim on windows: copy this file as AppData\Local\nvim\init.vim

" vimplug automatic installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" ft-man-plugin to show man pages
runtime ftplugin/man.vim

" load plugins
call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'altercation/vim-colors-solarized'
Plug 'preservim/nerdtree'
call plug#end()

filetype plugin indent on 

" indentation
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set autoindent

" show line numbers
set number

" leader key -- the q key is not a good option...
" let mapleader = "q"

" show visual clue that the leader key was pressed
set showcmd

" color scheme 
"colo evening 
"colo desert
"syntax on
"
syntax enable
set background=dark
colorscheme solarized

setlocal conceallevel=2

" key shortcut for opening nerdtree
map <C-n> :NERDTreeToggle<CR>

"" Copy to clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy

"" Paste from clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P

" break line but not in the middle of a word 
autocmd BufNewFile,BufRead *.txt,*.md set formatoptions=l
autocmd BufNewFile,BufRead *.txt,*.md set lbr

