" gvim on windows: copy this file as Users/user/_vimrc
" neovim on windows: copy this file as AppData\Local\nvim\init.vim

" Vimplug automatic installation
" neovim on windows: change the path to vimfiles/
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" wrap only at a character 
set linebreak

" encoding
set encoding=UTF-8
set fileencoding=UTF-8

" ft-man-plugin to show man pages
runtime ftplugin/man.vim

" Load plugins
call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-surround'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'altercation/vim-colors-solarized'
Plug 'NLKNGuyen/papercolor-theme'
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'rust-lang/rust.vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'dense-analysis/ale'
call plug#end()

filetype plugin indent on 

" Indentation
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set autoindent

" Show line numbers
set number

" Show visual clue that the leader key was pressed
set showcmd

"set t_Co=256

" color scheme 
"colo evening 
"colo desert
"syntax on
"
syntax enable
set background=dark
"colorscheme solarized
colorscheme PaperColor

setlocal conceallevel=2

" Key shortcut for opening nerdtree
map <C-n> :NERDTreeToggle<CR>

" Copy to clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy

" Paste from clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P

" Break line but not in the middle of a word 
autocmd BufNewFile,BufRead *.txt,*.md set formatoptions=l
autocmd BufNewFile,BufRead *.txt,*.md set lbr

" Use ctrl-[hjkl] to select the active split
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Show match as search proceeds
set incsearch
" Search hightlighting
set hlsearch

" Making Q harmless (no entering ex mode)
nnoremap Q <nop>

" Show eol and tabs with <leader>l
nmap <leader>l : set list!<CR>
set listchars=tab:»\ ,eol:¬

" match background color in gitgutter column
highlight clear SignColumn

" switch buffers by number
:nnoremap <F5> :buffers<CR>:buffer<Space>

" activate Goyo concentration mode
noremap <C-g> :Goyo<CR>

hi Terminal ctermbg=0 
"ctermfg=blue guibg=lightgrey guifg=blue
"
"let g:terminal_ansi_colors = [
"  \'#eeeeee', '#af0000', '#008700', '#5f8700',
"  \'#0087af', '#878787', '#005f87', '#444444',
"  \'#bcbcbc', '#d70000', '#d70087', '#8700af',
"  \'#d75f00', '#d75f00', '#005faf', '#005f87' ]

" rename  Buffers to B
command B Buffers
command F Files

" multiple options for :Files, with leader key and ctrl
nmap <leader>f :Files<CR>
nmap <silent><c-p> :Files<CR>
map _ :Rg<CR>

" show all buffers when there is only one tab open
let g:airline#extensions#tabline#enabled = 1

" Can use mouse to scroll or switch buffers
set mouse=a

"  edit multiple buffers without saving the modifications made to a buffer
"  while loading other buffers.
set hidden
