" gvim on windows: copy this file as Users/user/_vimrc
" neovim on windows: copy this file as AppData\Local\nvim\init.vim

" Vimplug automatic installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" encoding
set encoding=UTF-8
set fileencoding=UTF-8

" ft-man-plugin to show man pages
runtime ftplugin/man.vim

" Load plugins
call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'altercation/vim-colors-solarized'
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
call plug#end()

filetype plugin indent on 

" Indentation
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set autoindent

" Show line numbers
set number

" Leader key -- the q key is not a good option...
" let mapleader = "q"

" Show visual clue that the leader key was pressed
set showcmd

" color scheme 
"colo evening 
"colo desert
"syntax on
"
syntax enable
set background=dark
colorscheme solarized

setlocal conceallevel=2

" Key shortcut for opening nerdtree
map <C-n> :NERDTreeToggle<CR>

" Copy to clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy

" Paste from clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P

" Break line but not in the middle of a word 
autocmd BufNewFile,BufRead *.txt,*.md set formatoptions=l
autocmd BufNewFile,BufRead *.txt,*.md set lbr

" Use ctrl-[hjkl] to select the active split
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Show match as search proceeds
set incsearch
" Search hightlighting
set hlsearch

" Making Q harmless (no entering ex mode)
nnoremap Q <nop>

" Show eol and tabs with <leader>l
nmap <leader>l : set list!<CR>
set listchars=tab:»\ ,eol:¬

